name: flutter_food_recognition_app
description: Food recognition main app to build in devices.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_food_recognition_dependency_module:
    path: ../flutter_food_recognition_dependency_module
  flutter_food_recognition_core:
    path: ../flutter_food_recognition_core
  flutter_food_recognition_clarifai:
    path: ../flutter_food_recognition_clarifai
  flutter_food_recognition:
    path: ../flutter_food_recognition

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  mocktail: ^1.0.0
  flutter_native_splash: ^2.3.3
  icons_launcher: ^2.1.4

flutter:
  uses-material-design: true

  fonts:
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans/PTSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/PTSans/PTSans-Bold.ttf
          style: normal
          weight: 700
    - family: GoodBoy
      fonts:
        - asset: assets/fonts/GoodBoy/GoodBoy.otf
          style: normal
          weight: 400
  
  assets:
    - assets/images/food_camera.png
    - assets/images/food_gallery.png
    - assets/images/background.png
    - assets/images/food_image_example.jpg
    - assets/images/foods/
    - assets/images/failure/

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/splash/splash.jpg
  android_12:
    image: assets/images/splash/splash.jpg
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center
  web: false

icons_launcher:
  platforms:
    android:
      enable: true
      image_path: assets/images/icons_launcher/icon_launcher_android.png
    ios:
      enable: true
      image_path: assets/images/icons_launcher/icon_launcher_ios.png
    web:
      enable: false
    macos:
      enable: false
    windows:
      enable: false
    linux:
      enable: false
