final foodsEnglishToPortuguese = {
  "active dry yeast": "fermento biológico seco",
  "alfalfa sprouts": "broto de alfafa",
  "alouette": "alouette",
  "almond": "amêndoa",
  "almond oil": "óleo de amêndoa",
  "alphabets": "letrinhas",
  "american cheese": "queijo prato",
  "dish cheese": "queijo prato",
  "ammonia powder": "amônia",
  "anchovies": "anchova",
  "anellini": "argolinha",
  "angel hair pasta": "cabelo de anjo",
  "anise": "anis, erva-doce",
  "aniseed": "sementes de erva-doce",
  "apple": "maçã",
  "apple cider": "suco de maçã",
  "apricots": "damascos",
  "artichoke": "alcachofra",
  "artificial juice": "refresco artificial",
  "artificial sweetener": "adoçante artificial",
  "asparagus": "aspargo",
  "back beans": "feijão preto",
  "bacon": "bacon",
  "baghette": "baguete",
  "baking powder": "fermento químico",
  "baking soda": "bicarbonato de sódio",
  "barbecue": "churrasco",
  "baked goods": "assados",
  "barley": "cevada",
  "basil": "manjericão",
  "bay leaves": "folhas de louro",
  "bayleaf powder": "louro em pó",
  "bean sprouts": "broto de feijão",
  "bean": "feijão",
  "beef": "carne bovina",
  "beef jerky": "carne seca",
  "beer": "cerveja",
  "beet": "beterraba",
  "beet powder": "beterraba em pó",
  "blackberry": "framboesa preta",
  "blood sausage": "chouriço",
  "blueberry": "blueberry",
  "bologna": "mortadela",
  "boursin": "boursin",
  "brain": "cérebro",
  "brandy": "aguardente",
  "brazil nut": "castanha-do-pará",
  "bread": "pão",
  "breast": "bifes",
  "brie": "queijo brie",
  "broccoli": "brocolis",
  "broth": "caldo de galinha, carne e legumes leve",
  "brown sugar": "açucar mascavo",
  "brownie cake": "brownie",
  "brussels": "couve de bruxelas",
  "bulb": "cabeça de alho",
  "burger": "hamburger",
  "burgers or hamburgers": "hamburgueres",
  "burro bananas": "banana-prata",
  "butter": "manteiga",
  "buttermilk": "creme de leite",
  "cabbages": "repolhos",
  "caciocavallo": "caciocavallo",
  "cajun spice mix": "mistura de tempero tipo cajun",
  "cake": "bolo",
  "cake decorating sprinkles": "confeitos para decoração de bolos",
  "calabrese sausage": "linguiça calabresa defumada",
  "calzone": "calzone",
  "cambozola": "cambozola",
  "camembert": "camembert",
  "canadian bacon": "presunto canadense",
  "canapé": "canapés",
  "candied fruit": "frutas cristalizadas",
  "candies": "balas e doces em geral",
  "cannelloni": "canelone",
  "cantaloupe": "melão",
  "cape shark": "cação",
  "cappelletti": "capeleti",
  "capsicum": "pimentão em flocos",
  "caramels": "caramelos",
  "caraway": "alcarávia",
  "cardamom": "cardamomo",
  "carp": "carpa",
  "carrot": "cenoura",
  "carrot powder": "cenoura em pó",
  "casaba melon": "melão de casca amarela",
  "cashew": "cajú",
  "cashew nuts": "castanha-de-cajú",
  "cassava flour": "farinha de mandioca",
  "casserole": "cozidos",
  "catsup": "catchup",
  "cauli-flower": "couve-flor",
  "caviar": "caviar",
  "cayenne pepper powder": "pimenta cayenna em pó",
  "celery": "salsão, aipo",
  "celery ground": "aipo em pó",
  "celery salt": "sal de aipo",
  "cereal": "cereal",
  "champagne": "champanhe",
  "chantilly cream": "creme de chantilly",
  "cheddar": "cheddar",
  "cheese": "queijo",
  "cherries": "cerejas",
  "chervil": "cerefólio",
  "chest": "peito",
  "chestnuts": "castanha portuguesa",
  "chewing gun": "chiclete",
  "chicken wings": "asas de frango",
  "chicken": "frango",
  "chicken legs": "coxas de frango",
  "chicory": "chicória",
  "chilli pepper": "pimenta malagueta",
  "chilli powder": "mix de tempero mexicano",
  "chinese cabbage": "acelga",
  "chips": "salgadinhos",
  "chocolate": "chocolate",
  "chocolate bar": "chocolate em barra",
  "chocolate sprinkles": "chocolate granulado",
  "chocolates": "bombons",
  "chuck cuts": "carne de segunda",
  "chunkey bananas": "banana-prata",
  "ciabatta": "ciabatta",
  "cilantro": "coentro fresco",
  "cinnamon powder": "canela em pó",
  "cinnamon stick": "canela em pó",
  "cinnamon sugar": "canela com açúcar",
  "citric acid": "ácido cítrico",
  "clove": "dente de alho ou cravo",
  "coarse salt": "sal grosso",
  "cob": "milho na espiga",
  "cocktail": "coquetel",
  "cocktail fruit": "salada de frutas",
  "coconut": "coco",
  "cod": "bacalhau",
  "cola": "refrigerante de cola",
  "coffee": "café",
  "coffee and milk,": "café-com-leite",
  "collard greens": "couve-manteiga",
  "concentrated milk": "leite evaporado",
  "conchiglioni": "conchinhas",
  "condensed milk": "leite condensado",
  "condensed-milk flan": "pudim de leite condensado",
  "cookies": "cookies",
  "coppa salami": "copa",
  "coriander": "coentro em grãos e pó",
  "corn": "milho",
  "corn chips": "salgadinhos de milho",
  "corn flour": "fubá fino",
  "corn meal": "fubá médio",
  "cows milk": "leite de vaca",
  "crab": "carangueijo",
  "crayfish": "camarão de água doce",
  "cream": "creme",
  "cream of tartar": "creme tártaro",
  "crisp": "chips",
  "croissant": "croissant",
  "crostini": "torradinhas salgadas",
  "croutons": "cubinhos de pão torrado para salada e sopa",
  "crumbs": "farinha de rosca",
  "crushed": "erva seca",
  "cucumber": "pepino",
  "cumin": "cominho",
  "currants": "passas",
  "curry": "curry",
  "cut": "cortes",
  "dairy": "ovos e laticícios",
  "dandelions": "almeirão",
  "decorators sugar": "açucar cristal colorido",
  "dehydrated mushrooms": "funghi secci",
  "dende oil": "azeite de dendê",
  "dill": "endro",
  "dip": "paté",
  "dough": "massa crua",
  "draft beer": "chopp",
  "dragees drazay": "confeitos dourados e prateados",
  "dressing": "molho para salada",
  "dried bananas": "banana-passa",
  "dried shrimp": "camarão seco",
  "drink mix": "pó para refresco",
  "duck": "pato",
  "duck egg": "ovo de pata",
  "edam": "edam",
  "egg": "ovo",
  "eggplants": "berinjela",
  "emmental": "emmental",
  "ervilha seca": "dried peas",
  "escarole": "escarola",
  "farfalle": "gravatinha",
  "fatback": "toicinho fresco ou couro de porco",
  "fennel": "erva-doce",
  "fennel seeds": "sementes de erva-doce",
  "feta": "feta",
  "fettuccine": "fettuccineo",
  "fig": "figos",
  "fine herbs": "ervas finas",
  "fish": "peixe",
  "flakes": "flocos",
  "flesh": "polpa",
  "french fries": "batatas fritas",
  "french roll": "pãozinho francês",
  "fresh peas": "ervilhas frescas",
  "frost": "cobertura de bolo",
  "fruit": "frutas",
  "fusilli": "parafuso",
  "garlic": "alho",
  "gin": "gim",
  "ginger": "gengibre",
  "gnocchi": "nhoque",
  "golden raisins": "passas claras",
  "gorgonzola": "gorgonzola",
  "gouda": "gouda",
  "granulated sugar": "açucar cristal",
  "grapefruit": "toranja",
  "grape": "uva",
  "gravy": "molho tipo ferrugem",
  "green beans": "vagem",
  "green papaya": "mamão comum",
  "green cabbage": "repolho verde",
  "green onion": "cebolinha",
  "grits": "grãos",
  "ground beef": "carne moída",
  "gruyière": "gruyière",
  "guar gum": "agar-agar",
  "guava": "goiaba",
  "ham": "presunto",
  "hazelnuts": "avelãs",
  "heart": "coração",
  "hearts of palms": "palmito",
  "herbal salt": "sal com ervas",
  "honey": "mel",
  "icecream": "sorvete",
  "instant noodles": "macarrão tipo miojo",
  "italian bread": "pão italiano",
  "italian sausage": "linguiça",
  "jackfruit": "jaca",
  "jam": "geléia",
  "jamaican pepper": "pimenta da jamaica",
  "jell-o": "gelatina",
  "jelly": "geléia",
  "jelly beans": "balinhas de goma",
  "jerked beef": "carne seca",
  "jimmies": "granulado colorido",
  "juice": "suco",
  "juniper": "zimbro",
  "ketchup": "ketchup",
  "key lime": "nosso limão",
  "kiwi": "kiwi",
  "kummel": "kümmel",
  "kumquat": "laranjinhas japonesas",
  "lamb": "cordeiro",
  "lard": "banha de porco",
  "layer cake": "bolo de camadas",
  "leavens": "leveduras",
  "legume": "legumes",
  "leek": "alho poró",
  "lemon": "limão amarelo",
  "lemon peel": "casca de limão",
  "lentilhas": "lentils",
  "lettuce": "alface",
  "lime juice": "limonada",
  "liqueur": "licor",
  "litchi": "lichívia",
  "liver": "fígado",
  "loaf": "baguete",
  "lobster": "lagosta",
  "loin cuts": "lombo",
  "lollipop": "pirulito",
  "monosodium glutamate": "glutamato monossódico",
  "mace": "macis",
  "mango": "manga",
  "manzano bananas": "banana-maçã",
  "margarine": "margarina",
  "marine algae": "alga marinha",
  "marjoram": "manjerona",
  "marmalade": "geléia cítrica",
  "mashed potatoes": "purê de batatas",
  "mayonnese": "maionese",
  "meat": "carne",
  "meat tenderizer": "amaciante de carne",
  "membrillo": "marmelada",
  "milk": "leite",
  "milk and tea": "leite-com-chá",
  "mineral water": "água mineral sem gás",
  "mint": "hortelã e menta",
  "miso": "missô",
  "molasses": "melado",
  "montbriac": "montbriac",
  "mortadella bologna": "mortadela",
  "mousse": "mousse",
  "mozzarella": "muçarela",
  "murcott": "mexerica morgot",
  "mush": "mingau",
  "mushrooms": "cogumelos",
  "mussels": "mexilhões",
  "mustard": "mostarda",
  "mustard yellow and black seeds": "mostarda comum e preta",
  "nectarines": "nectarinas",
  "nonpareils": "bolinhas coloridas",
  "noodles": "sopa de massa",
  "nutmeg": "noz moscada",
  "oat meal": "farinha de aveia",
  "octopus": "polvo",
  "offal": "múdos",
  "okra": "quiabo",
  "olive oil": "azeite de oliva",
  "olives": "azeitonas",
  "omelet": "omelete",
  "onion": "cebola",
  "orange": "laranja",
  "orange peel": "casca de laranja",
  "oregano": "orégano",
  "orzo": "arroz",
  "oyesters": "ostras",
  "palm oil": "azeite de dendê",
  "papaya": "papaia",
  "paprika hot": "páprica picante",
  "paprika smoked": "páprica defumada",
  "paprika sweet": "páprica doce",
  "parmesan": "parmesão",
  "parsley": "salsa",
  "parsley and chives": "cheiro-verde",
  "passion fruit": "maracujá",
  "pasta": "massas, macarrão",
  "pastry": "massa",
  "peaches": "pêssegos",
  "peanuts": "amendoins",
  "pear": "pera",
  "peel": "casca",
  "penne": "penne",
  "pepper": "pimenta",
  "pepperoni": "calabresa",
  "persimmon": "caqui",
  "pickled onions": "cebolinha em conserva",
  "pickles": "picles",
  "pie": "torta",
  "pie pastry": "massa de torta",
  "pine nut": "pinoli",
  "pineapple": "abacaxi",
  "pink pepper": "pimenta rosa",
  "pinoli": "pinoli",
  "pinto beans": "feijão rajadinho",
  "pistachio nut": "pistache",
  "pit": "caroço",
  "pita": "pão sírio",
  "pizza": "pizza",
  "plantain": "banana-da-terra",
  "plums": "ameixas",
  "polenta meal": "fubá grosso",
  "pomegranade": "romã",
  "pop": "refrigerantes",
  "poppy seeds": "semente de papoula",
  "popsicle": "picolé",
  "pork": "carne de porco",
  "pork chops": "costeletas de porco",
  "port salut": "port salut",
  "potato": "batata",
  "potato chips": "batatas fritas",
  "provence herbs": "ervas de provence",
  "provolone": "provolone",
  "prunes": "ameixas pretas secas",
  "pudding": "pudim",
  "puff pastry": "massa folhada",
  "pumpkin": "abóbora",
  "quail egg": "ovo de codorna",
  "quiche": "quiche",
  "quince": "marmelo",
  "radish": "rabanete",
  "raisins": "passas comuns",
  "rangpur lime": "limão vermelho",
  "rapberry": "amora",
  "red chilli pepper": "pimenta malagueta vermelha",
  "red meats": "carnes vermelhas",
  "red pepper flakes": "pimenta calabresa",
  "refreshment": "refresco",
  "rib cuts": "costela",
  "rice": "arroz",
  "rice and beans": "arroz com feijão",
  "rice pudding": "arroz doce",
  "ricotta": "ricota",
  "ritzo cracker": "biscoitinhos tipo salclic",
  "roll or buns": "pãozinho",
  "rosemary": "alecrim",
  "round cuts": "traseiro",
  "rucola": "rúcula",
  "rum": "rum",
  "rye": "centeio",
  "saffron": "açafrão",
  "sage": "sálvia",
  "salad": "salada",
  "salami": "salame",
  "salmon": "salmão",
  "salsa": "molho tipo mexicano",
  "salt cod": "bacalhau salgado",
  "sanduiche bread": "pão de forma",
  "sandwich": "sanduiche",
  "sardines": "sardinhas",
  "sauce": "molhos em geral",
  "scrambled eggs": "ovos mexidos",
  "sea salt": "sal marinho",
  "seafood": "frutos do mar",
  "seasonings": "temperos",
  "seed": "semente",
  "seeds": "grãos ou sementes de temperos",
  "sesame seeds": "gergelim",
  "shellfish": "crustáceos",
  "shortening": "margarina culinária",
  "shrimp": "camarão",
  "sirian pepper": "pimenta síria",
  "sirloin": "contrafilé",
  "skin": "pele",
  "smoked salt": "sal defumado",
  "smoked sausage": "lingüiça defumada",
  "snow pea": "ervilha fresca",
  "snowflackes": "confeitinhos coloridos",
  "soda": "soda",
  "soja": "soy",
  "soup": "sopa",
  "soup bones": "ossos para sopa",
  "soy sauce": "shoyu",
  "soybean sprouts": "broto de soja",
  "spaghetti": "espaguete",
  "sparkling sugar": "açucar cristal multicor",
  "spinach": "espinafre",
  "spinach powder": "espinafre em pó",
  "spread": "paté",
  "squid": "lula",
  "star fruit": "carambola",
  "star anise": "anis estrelado",
  "steak": "bife",
  "stems": "caule",
  "stew": "cozidos de carne com ou sem feijão",
  "stew meat": "carne de segunda",
  "strawberry": "morangos",
  "sugar": "açucar",
  "suiss": "suiço",
  "summer savary": "segurelha",
  "sweep potato": "batata doce",
  "sweet corn": "milho verde",
  "sweet peppers": "pimentões",
  "syrop": "xarope",
  "t-bone steak": "tibone",
  "taglierini": "talharim",
  "tamarind": "tamarindo",
  "tangerine": "mexerica",
  "tapioca pearls": "sagú",
  "tapioca pudding": "pudim de tapioca",
  "tarragon": "estragão",
  "tea": "chá",
  "tenderloin": "filé mignon",
  "thyme": "tomilho",
  "tofu": "tofu",
  "tomato": "tomate",
  "tongue": "língua",
  "tonic water": "água tonica",
  "topping": "cobertura",
  "tortillas chips": "tortilhas",
  "tripe": "dobradinha",
  "tubetti": "tubinhos",
  "tuna": "atum",
  "turkey": "peru",
  "turmeric": "açafrão comum",
  "turnip": "nabo",
  "ugli fruit": "mexerica ponkan",
  "urucum": "urucum",
  "vanilla": "baunilha",
  "vanilla sugar": "açúcar vanile",
  "veal": "vitela",
  "vegetable": "vegetais",
  "vinaigrette": "vinagrete",
  "vodka": "vodca",
  "waffer": "waffer",
  "waffers": "waffers",
  "walnuts": "nozes",
  "wasabi powder": "raiz forte",
  "water cracker": "biscoitos de água",
  "watercress": "agrião",
  "watermelon": "melancia",
  "wheat": "trigo",
  "whipped cream": "chantilly",
  "whiskey": "uísque",
  "white and black pepper": "pimenta do reino",
  "white meats": "carnes brancas",
  "wine": "vinho",
  "wine red and white": "vinho tinto e branco",
  "winter squash": "squash",
  "wrap": "salgadinhos envoltos em massa",
  "yams": "inhame",
  "yeast": "fermento biológico",
  "yellow cavendish banana": "banana nanica",
  "yellow food coloring": "colorífico",
  "yogurt": "iogurte",
  "zahtar": "zattar",
  "zucchine": "abobrinha",
  "apple juice": "suco de maçã",
  "bbq": "churrasco",
  "bell pepper flakes": "pimentão em flocos",
  "bell peppers": "pimentões",
  "buffalo milk mozzarella": "buffalo milk mozzarella",
  "catchup": "catchup",
  "chives": "cebolinha",
  "coarse": "farinha de rosca",
  "coarse sugar": "açucar cristal colorido",
  "corn starch": "amido de milho",
  "crawfish": "camarão de água doce",
  "fine": "farinha de rosca",
  "fish eggs": "caviar",
  "flour": "farinha de trigo",
  "frankfurter": "salsichão",
  "glacé fruits": "frutas cristalizadas",
  "hot italian sausage": "linguiça defumada",
  "icecream cone": "sorvete de casquinha",
  "manioc flour": "farinha de mandioca",
  "marrons": "castanha portuguesa",
  "mayo": "maionese",
  "menudo": "bucho",
  "polenta": "polenta",
  "pork leg": "lombo de porco",
  "pulp": "polpa",
  "red cabbage": "repolho roxo",
  "salad fruit": "salada de frutas",
  "self-rising flour": "farinha com fermento",
  "shark": "cação",
  "sparkling": "espumante",
  "stock": "caldo de galinha, carne e legumes encorpado",
  "stone": "caroço",
  "tapioca root": "mandioca",
  "tapioca starch": "polvilho",
  "wheat flour": "farinha de trigo",
  "white coffee": "café-com-leite",
};
